create table if not exists public.time_tracking_sessions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  memory_item_id integer null references public.memory_items(id) on delete set null,
  title text null,
  notes text null,
  started_at timestamptz not null default now(),
  ended_at timestamptz null,
  duration_seconds integer null,
  is_running boolean not null default true,
  stop_reason text null,
  last_activity_at timestamptz null
);

create index if not exists time_tracking_sessions_memory_item_id_idx
  on public.time_tracking_sessions (memory_item_id);

create index if not exists time_tracking_sessions_started_at_idx
  on public.time_tracking_sessions (started_at);

create index if not exists time_tracking_sessions_is_running_idx
  on public.time_tracking_sessions (is_running);
